version: '3.8'

services:
  app:
    build: .
    ports: 
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - .:/app
    entrypoint: ["sh", "-c", "npm run dev"]

  database:
    container_name: database
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: database
    ports:
      - "5432:5432"
