services:
  database:
    container_name: database
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: database
    ports:
      - "5432:5432"